---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 34.718834
  longitude: -86.778134
  elevation: 214.884
  time_zone: America/Chicago
  plugins:
    HASS:
      type: hass
      notify_key: !secret notify_me_key
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
#logs:
#  main_log:
#    filename: /var/log/appdaemon/appdaemon.log
#  access_log:
#    filename: /var/log/appdaemon/access.log
#  error_log:
#    filename: /var/log/appdaemon/error.log
#  diag_log:
#    filename: /var/log/appdaemon/diag.log
#    log_generations: 5
#    log_size: 1024
#    format: "{asctime} {levelname:<8} {appname:<10}: {message}"6
