---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 34.718834
  longitude: -86.778134
  elevation: 214.884
  time_zone: America/Chicago
  plugins:
    HASS:
      type: hass
      notify_key: !secret notify_me_key
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
