- id: '1531343546892'
  alias: Coffee Timer
  trigger:
  - entity_id: switch.03200121dc4f221ad1cf_2
    for:
      minutes: 30
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.03200121dc4f221ad1cf_2
    service: switch.turn_off
- id: '1531347206490'
  alias: Restart Humidifier
  initial_state: 'off'
  trigger:
  - entity_id: switch.humidifier
    for:
      minutes: 60
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.humidifier
    service: switch.turn_on
  - data:
      entity_id: automation.restart_humidifier
    service: automation.turn_off
- id: '1531918562375'
  alias: Lights on at Early Sunset
  trigger:
  - event: sunset
    offset: -01:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.evening_early_lights
    service: switch.turn_on
- id: '8881234567890'
  alias: Lights on at Sunset
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.evening_lights
    service: switch.turn_on
  - data:
      entity_id: group.accent_lights
    service: switch.turn_on
- id: '1532102191810'
  alias: Lights out at Bedtime
  trigger:
  - entity_id: binary_sensor.sleepnumber_bill_bill_is_in_bed
    platform: state
    to: 'on'
  - entity_id: binary_sensor.sleepnumber_bill_cricket_is_in_bed
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.sleepnumber_bill_bill_is_in_bed
    state: 'on'
  - condition: state
    entity_id: binary_sensor.sleepnumber_bill_cricket_is_in_bed
    state: 'on'
  action:
  - data:
      entity_id: group.living_area_lights
    service: switch.turn_off
  - data:
      entity_id: switch.fan_control
    service: switch.turn_on
- id: '1532212236193'
  alias: Late Night Light
  trigger:
  - entity_id: binary_sensor.sleepnumber_bill_bill_is_in_bed
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.sleepnumber_bill_cricket_is_in_bed
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: '22:00:00'
    before: 06:00:00
    condition: time
  action:
  - data:
      entity_id: switch.0120099868c63aa67ad8_4
    service: switch.turn_on
  - data:
      entity_id: group.counter_lights
    service: switch.turn_on
- id: '1532093963927'
  alias: HVAC Balancing
  trigger:
  - event_data:
      entity_id: sensor.downstairs_thermostat_temperature
    event_type: state_changed
    platform: event
  - event_data:
      entity_id: sensor.upstairs_thermostat_temperature
    event_type: state_changed
    platform: event
  condition: []
  action:
  - service: python_script.fan_control
- id: '1534730679270'
  alias: Lights Off When Away
  trigger:
  - at: '23:15:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.bayberry_away
    state: 'on'
  action:
  - data:
      entity_id: group.all_indoor_lights
    service: switch.turn_off
- id: '1535862789511'
  alias: Away Monitor
  trigger:
  - entity_id: device_tracker.bill_cell
    platform: state
  - entity_id: device_tracker.cricket_cell
    platform: state
  condition: []
  action:
  - data_template:
      entity: '{{ trigger.entity_id }}'
    service: python_script.away_monitor
- id: '1537990954788'
  alias: Lights On When Away
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.away_lights
    service: switch.turn_on
- id: '1542775976127'
  alias: Watch TV - Start
  trigger:
  - entity_id: remote.harmony_hub
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.wemo_alpha
    service: switch.turn_off
- id: '1542776135207'
  alias: Watch TV - Stop
  trigger:
  - entity_id: remote.harmony_hub
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.wemo_alpha
    service: switch.turn_on
  - data:
      entity_id: automation.restart_humidifier
    service: automation.turn_off
- id: '1543243906037'
  alias: Lights On For Weekday Mornings
  trigger:
  - at: 05:15
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday
    state: 'on'
  action:
  - data:
      entity_id: group.morning_lights
    service: switch.turn_on
- id: '1531365279143'
  alias: Kyles Reading Light Timer
  trigger:
  - entity_id: switch.wemo_bravo
    for:
      minutes: 20
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.wemo_bravo
    service: switch.turn_off
