- id: '1531149972632'
  alias: Car Arrives Home
  trigger:
  - entity_id: cover.left_bay
    from: closed
    platform: state
    to: open
  - entity_id: cover.right_bay
    from: closed
    platform: state
    to: open
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      entity_id: switch.sofa_lamp
    service: switch.turn_on
- id: '1531347206490'
  alias: Auto Off Light
  initial_state: 'off'
  trigger:
  - entity_id: switch.entry_lamp
    for:
      minutes: 2
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.entry_lamp
    service: switch.turn_off
- id: '1531918562375'
  alias: Sunset Early Lights
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.entry_lamp
    service: switch.turn_on
  - data:
      entity_id: switch.sofa_lamp
    service: switch.turn_on
- id: '1532102191810'
  alias: Lights out at Bedtime
  trigger:
  - entity_id: binary_sensor.sleepnumber_bill_bill_is_in_bed
    platform: state
    to: 'on'
  - entity_id: binary_sensor.sleepnumber_bill_cricket_is_in_bed
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.sleepnumber_bill_bill_is_in_bed
    state: 'on'
  - condition: state
    entity_id: binary_sensor.sleepnumber_bill_cricket_is_in_bed
    state: 'on'
  action:
  - data:
      entity_id: group.living_area_lights
    service: switch.turn_off
- id: '1532212236193'
  alias: Late Night Light
  trigger:
  - entity_id: binary_sensor.sleepnumber_bill_bill_is_in_bed
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.sleepnumber_bill_cricket_is_in_bed
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '22:00:00'
    before: 06:00:00
    condition: time
  action:
  - data:
      entity_id: switch.sofa_lamp
    service: switch.turn_on
- id: '1532093963927'
  alias: HVAC Balancing
  trigger:
  - event_data:
      entity_id: sensor.downstairs_thermostat_temperature
    event_type: state_changed
    platform: event
  - event_data:
      entity_id: sensor.upstairs_thermostat_temperature
    event_type: state_changed
    platform: event
  condition: []
  action:
  - service: python_script.fan_control
