- id: '1531343546892'
  alias: Coffee Timer
  trigger:
  - entity_id: switch.03200121dc4f221ad1cf_2
    for:
      minutes: 30
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.03200121dc4f221ad1cf_2
    service: switch.turn_off
- id: '1531347206490'
  alias: Restart Humidifier
  initial_state: 'off'
  trigger:
  - entity_id: switch.humidifier
    for:
      minutes: 60
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.humidifier
    service: switch.turn_on
  - data:
      entity_id: automation.restart_humidifier
    service: automation.turn_off
- id: '1531918562375'
  alias: Lights on at Early Sunset
  trigger:
  - event: sunset
    offset: -01:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.evening_early_lights
    service: switch.turn_on
- id: '8881234567890'
  alias: Lights on at Sunset
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.evening_lights
    service: switch.turn_on
  - data:
      entity_id: group.accent_lights
    service: switch.turn_on
- id: '1532102191810'
  alias: Lights out at Bedtime
  trigger:
  - entity_id: binary_sensor.sleepnumber_bill_bill_is_in_bed
    platform: state
    to: 'on'
  - entity_id: binary_sensor.sleepnumber_bill_cricket_is_in_bed
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.sleepnumber_bill_bill_is_in_bed
    state: 'on'
  - condition: state
    entity_id: binary_sensor.sleepnumber_bill_cricket_is_in_bed
    state: 'on'
  - condition: state
    entity_id: remote.harmony_hub
    state: 'off'
  action:
  - data:
      entity_id: group.living_area_lights
    service: switch.turn_off
  - data:
      entity_id: switch.fan_control
    service: switch.turn_on
- id: '1532212236193'
  alias: Late Night Light
  trigger:
  - entity_id: binary_sensor.sleepnumber_bill_bill_is_in_bed
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.sleepnumber_bill_cricket_is_in_bed
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: '22:00:00'
    before: 06:00:00
    condition: time
  action:
  - data:
      entity_id: group.late_night_lights
    service: switch.turn_on
- id: '1532093963927'
  alias: HVAC Balancing
  trigger:
  - event_data:
      entity_id: sensor.downstairs_thermostat_temperature
    event_type: state_changed
    platform: event
  - event_data:
      entity_id: sensor.upstairs_thermostat_temperature
    event_type: state_changed
    platform: event
  condition: []
  action:
  - service: python_script.fan_control
- id: '1534730679270'
  alias: Lights Off When Away
  trigger:
  - at: '23:15:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.bayberry_away
    state: 'on'
  action:
  - data:
      entity_id: group.all_indoor_lights
    service: switch.turn_off
- id: '1537990954788'
  alias: Lights On When Away
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.away_lights
    service: switch.turn_on
- id: '1542775976127'
  alias: Watch TV - Start
  trigger:
  - entity_id: remote.harmony_hub
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.0120099868c63aa67ad8_1
    service: switch.turn_off
- id: '1542776135207'
  alias: Watch TV - Stop
  trigger:
  - entity_id: remote.harmony_hub
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.0120099868c63aa67ad8_1
    service: switch.turn_on
  - data:
      entity_id: automation.restart_humidifier
    service: automation.turn_off
- id: '1543243906037'
  alias: Lights On For Weekday Mornings
  trigger:
  - at: 05:15
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday
    state: 'on'
  action:
  - data:
      entity_id: group.morning_lights
    service: switch.turn_on
- id: '1531365279143'
  alias: Kyles Reading Light Timer
  trigger:
  - entity_id: switch.wemo_bravo
    for:
      minutes: 20
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.wemo_bravo
    service: switch.turn_off
- id: '1551361947987'
  alias: Exterior Lights on at Sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.driveway_light
    service: switch.turn_on
  - data:
      entity_id: switch.frontdoor_light
    service: switch.turn_on
- id: '1551362916030'
  alias: Exterior Lights Off
  trigger:
  - at: '21:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: timer.motion_debounce
    service: timer.start
  - data:
      entity_id: switch.driveway_light
    service: switch.turn_off
  - data:
      entity_id: switch.frontdoor_light
    service: switch.turn_off
- id: '1531353746820'
  alias: Patio Light Timer
  trigger:
  - entity_id: switch.patio_light
    for:
      minutes: 30
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.patio_light
    service: switch.turn_off
- id: '1555681619395'
  alias: Front Door Motion
  trigger:
  - entity_id: binary_sensor.ring_front_door_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.frontdoor_light
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: switch.frontdoor_light
    service: switch.turn_on
  - delay: 00:05:00
  - data:
      entity_id: switch.frontdoor_light
    service: switch.turn_off
- id: '1555681619396'
  alias: Driveway Motion
  trigger:
  - entity_id: binary_sensor.ring_driveway_cam_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: timer.motion_debounce
    state: idle
  - condition: state
    entity_id: switch.driveway_light
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: switch.driveway_light
    service: switch.turn_on
  - delay: 00:05:00
  - data:
      entity_id: timer.motion_debounce
    service: timer.start
  - data:
      entity_id: switch.driveway_light
    service: switch.turn_off
- alias: Floor Fan Monitor On
  trigger:
    platform: state
    entity_id: fan.bedroom_fan
  action:
  - condition: template
    value_template: '{{ state_attr(''fan.bedroom_fan'', ''speed'') == ''high'' }}'
  - service: switch.turn_on
    entity_id: switch.wemo_alpha
  id: 9354c53b84654dbeb7f785f4824c13fe
- alias: Floor Fan Monitor Off
  trigger:
    platform: state
    entity_id: fan.bedroom_fan
  action:
  - condition: template
    value_template: '{{ state_attr(''fan.bedroom_fan'', ''speed'') != ''high'' }}'
  - service: switch.turn_off
    entity_id: switch.wemo_alpha
  id: 9486188e8a534ef8a0794bd0ccdd1768
- id: '1559082914918'
  alias: Pollen Monitor
  trigger:
  - at: '18:00:00'
    platform: time
  condition: []
  action:
  - service: python_script.pollen_monitor
- id: '1569264293957'
  alias: Arrive Home from Work
  trigger:
  - entity_id: sensor.bill_location
    platform: state
    to: Home
  - entity_id: sensor.cricket_location
    platform: state
    to: Home
  condition:
  - after: '16:00:00'
    before: '18:00:00'
    condition: time
  action:
  - alias: ''
    data:
      entity_id: cover.right_bay
    service: cover.open_cover
  - data:
      entity_id: cover.left_bay
    service: cover.open_cover
- id: '1572571564942'
  alias: Washing Machine Power On
  description: ''
  trigger:
  - entity_id: switch.washing_machine
    for: 0:01:00
    platform: state
    to: 'off'
  condition: []
  action:
  - alias: ''
    data:
      entity_id: switch.washing_machine
    service: switch.turn_on
