# MQTT
mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-7718
  keepalive: 60
  #username: !secret mqtt_username
  #password: !secret mqtt_password
  discovery: true
  discovery_prefix: ha-7718

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 34.718548
  longitude: -86.778091
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: US/Central
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:
  themes:
    midnight:
      primary-color: "#5294E2"
      accent-color: "#E45E65"
      dark-primary-color: "var(--accent-color)"
      light-primary-color: "var(--accent-color)"
      primary-text-color: "#FFFFFF"
      text-primary-color: "var(--primary-text-color)"
      secondary-text-color: "#5294E2"
      disabled-text-color: "#7F848E"
      label-badge-border-color: "green"
      primary-background-color: "#383C45"
      secondary-background-color: "#383C45"
      divider-color: "rgba(0, 0, 0, .12)"
      table-row-background-color: "#353840"
      table-row-alternative-background-color: "#3E424B"
      paper-listbox-color: "var(--primary-color)"
      paper-listbox-background-color: "#2E333A"
      paper-grey-50: "var(--primary-text-color)"
      paper-grey-200: "#414A59"
      paper-card-header-color: "var(--accent-color)"
      paper-card-background-color: "#434954"
      paper-dialog-background-color: "#434954"
      paper-item-icon-color: "var(--primary-text-color)"
      paper-item-icon-active-color: "#F9C536"
      paper-item-icon_-_color: "green"
      paper-item-selected_-_background-color: "#434954"
      paper-tabs-selection-bar-color: "green"
      label-badge-red: "var(--accent-color)"
      label-badge-text-color: "var(--primary-text-color)"
      label-badge-background-color: "#2E333A"
      paper-toggle-button-checked-button-color: "var(--accent-color)"
      paper-toggle-button-checked-bar-color: "var(--accent-color)"
      paper-toggle-button-checked-ink-color: "var(--accent-color)"
      paper-toggle-button-unchecked-button-color: "var(--disabled-text-color)"
      paper-toggle-button-unchecked-bar-color: "var(--disabled-text-color)"
      paper-toggle-button-unchecked-ink-color: "var(--disabled-text-color)"
      paper-slider-knob-color: "var(--accent-color)"
      paper-slider-knob-start-color: "var(--accent-color)"
      paper-slider-pin-color: "var(--accent-color)"
      paper-slider-active-color: "var(--accent-color)"
      paper-slider-container-color: "linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat"
      paper-slider-secondary-color: "var(--secondary-background-color)"
      paper-slider-disabled-active-color: "var(--disabled-text-color)"
      paper-slider-disabled-secondary-color: "var(--disabled-text-color)"
      google-red-500: "#E45E65"
      google-green-500: "#39E949"

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: https://bakerbug.duckdns.org:8123
  ssl_certificate: /home/homeassistant/.homeassistant/fullchain.pem
  ssl_key: /home/homeassistant/.homeassistant/privkey.pem
  api_password: !secret api_key
  cors_allowed_origins:
    - http://10.99.10.7:7080

duckdns:
  domain: bakerbug
  access_token: !secret duckdns_token

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
    use_include_order: True
    include:
        entities:
            - weather.dark_sky
            - sun.sun
            - sensor.moon
            - sensor.upstairs_thermostat_temperature
            - sensor.downstairs_thermostat_temperature
            - sensor.upstairs_thermostat_humidity
            - sensor.downstairs_thermostat_humidity
            - sensor.upstairs_thermostat_hvac_state
            - sensor.downstairs_thermostat_hvac_state
            - fan.ceiling_fan
            - sensor.fan_speed
            - binary_sensor.bayberry_away
            - cover.left_bay
            - cover.right_bay
            - sensor.sleepnumber_bill_bill_sleepnumber
            - sensor.sleepnumber_bill_cricket_sleepnumber
            - binary_sensor.sleepnumber_bill_bill_is_in_bed
            - binary_sensor.sleepnumber_bill_cricket_is_in_bed
            - media_player.living_room
            - media_player.bedroom_tv
            - switch.bedroom_lamp
            - switch.bills_lamp
            - switch.crickets_lamp
            - switch.entry_lamp
            - switch.sofa_lamp
            - switch.0120099868c63aa67ad8_3
            - switch.0120099868c63aa67ad8_4
            - switch.sink_light
            - group.counter_lights
            - group.ceiling_lights
    exclude:
        domains:
            - automation
        entities:
            - sensor.bayberry_eta
            - sensor.weather_symbol
            - group.bed
            - group.garage

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Custom Sensors
sensor:
  - platform: yr
    name: Weather
  - platform: moon
  - platform: template
    sensors:
      fan_speed:
        friendly_name: "Ceiling Fan Speed"
        value_template: "{{ states.fan.ceiling_fan.attributes.speed }}"
      sun_elevation:
        friendly_name: "Sun Elevation"
        value_template: "{{ states.sun.sun.attributes.elevation }}"

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Python script support
python_script:

# Garage Doors
cover:
  - platform: myq
    hidden: true
    username: !secret chamberlain_username
    password: !secret chamberlain_password
    type: chamberlain
    
# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  
# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    
# Plex
#media_player:
#  - platform: plex

# Sleep Number Bed
sleepiq:
  username: !secret sleepnumber_user
  password: !secret sleepnumber_password

# Slack
notify:
  - name: Slack_Assistant
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#home'

# Tuya - Smart Life - Smart Power Strips
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1
  platform: 'smart_life'

# Living Room Fan
fan:
  - platform: mqtt
    name: Ceiling Fan
    state_topic: "ha-7718/Ceiling Fan/switch"
    command_topic: "ha-7718/Ceiling Fan/switch"
    payload_on: "on"
    payload_off: "off"
    speed_state_topic: "ha-7718/Ceiling Fan/level"
    speed_command_topic: "ha-7718/Ceiling Fan/level"
    payload_low_speed: 33
    payload_medium_speed: 66
    payload_high_speed: 100
    retain: true
