# MQTT
mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-7718
  keepalive: 60
  #username: !secret mqtt_username
  #password: !secret mqtt_password
  discovery: true
  discovery_prefix: ha-7718

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 34.718548
  longitude: -86.778091
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: US/Central
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   # uncomment this to enable backwards compatible API password support
   # - type: legacy_api_password

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend: !include frontend.yaml

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: https://bakerbug.duckdns.org:8123
  ssl_certificate: /home/homeassistant/.homeassistant/fullchain.pem
  ssl_key: /home/homeassistant/.homeassistant/privkey.pem
  api_password: !secret api_key
  cors_allowed_origins:
    - http://10.99.10.7:7080

duckdns:
  domain: bakerbug
  access_token: !secret duckdns_token

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
    use_include_order: True
    include:
        entities:
            - weather.dark_sky
            - sun.sun
            - sensor.moon
            - binary_sensor.bayberry_away
            - device_tracker.bill_cell
            - device_tracker.cricket_cell
            - sensor.upstairs_thermostat_temperature
            - sensor.downstairs_thermostat_temperature
            - sensor.upstairs_thermostat_humidity
            - sensor.downstairs_thermostat_humidity
            - sensor.upstairs_thermostat_hvac_state
            - sensor.downstairs_thermostat_hvac_state
            - fan.ceiling_fan
            - sensor.fan_speed
            - switch.humidifier
            - cover.left_bay
            - cover.right_bay
            - sensor.sleepnumber_bill_bill_sleepnumber
            - sensor.sleepnumber_bill_cricket_sleepnumber
            - binary_sensor.sleepnumber_bill_bill_is_in_bed
            - binary_sensor.sleepnumber_bill_cricket_is_in_bed
            - media_player.living_room
            - media_player.bedroom_tv
            - switch.bedroom_lamp
            - switch.04200320b4e62d1291c4_1
            - switch.04200320b4e62d1291c4_4
            - switch.entry_lamp
            - switch.sofa_lamp
            - switch.0120099868c63aa67ad8_3
            - switch.0120099868c63aa67ad8_4
            - switch.sink_light
            - group.counter_lights
            - group.ceiling_lights
    exclude:
        domains:
            - automation
        entities:
            - sensor.bayberry_eta
            - sensor.weather_symbol
            - group.bed
            - group.garage
            - switch.fan_control

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Custom Sensors
sensor:
  - platform: time_date
    display_options:
      - 'time'
  - platform: yr
    name: Weather
  - platform: moon
  - platform: template
    sensors:
      fan_speed:
        friendly_name: "Ceiling Fan Speed"
        value_template: "{{ states.fan.ceiling_fan.attributes.speed }}"
      sun_elevation:
        friendly_name: "Sun Elevation"
        value_template: "{{ states.sun.sun.attributes.elevation }}"

# Custom Switches
switch:
  - platform: template
    switches:
      fan_control:
        friendly_name: "Fan Control"
        value_template: "{{ is_state('automation.hvac_balancing', 'on') }}"
        turn_on:
          - service: automation.turn_on
            data:
              entity_id: automation.hvac_balancing
          - service: python_script.fan_control
        turn_off:
          service: automation.turn_off
          data:
            entity_id: automation.hvac_balancing
      humidifier:
        friendly_name: "Humidifier"
        value_template: "{{ is_state('switch.accessory_alpha', 'on') }}"
        turn_on:
          - service: switch.turn_on
            data:
              entity_id: switch.accessory_alpha
        turn_off:
          - service: automation.turn_on
            data:
              entity_id: automation.restart_humidifier
          - service: switch.turn_off
            data:
              entity_id: switch.accessory_alpha

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Python script support
python_script:

# Garage Doors
cover:
  - platform: myq
    hidden: true
    username: !secret chamberlain_username
    password: !secret chamberlain_password
    type: chamberlain
    
# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  
# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    
# Plex
#media_player:
#  - platform: plex

# Sleep Number Bed
sleepiq:
  username: !secret sleepnumber_user
  password: !secret sleepnumber_password

# Slack
notify:
  - name: Slack_Assistant
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#home'

# Tuya - Smart Life - Smart Power Strips
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1
  platform: 'smart_life'

# Living Room Fan
fan:
  - platform: mqtt
    name: Ceiling Fan
    state_topic: "ha-7718/Ceiling Fan/switch"
    command_topic: "ha-7718/Ceiling Fan/switch"
    payload_on: "on"
    payload_off: "off"
    speed_state_topic: "ha-7718/Ceiling Fan/level"
    speed_command_topic: "ha-7718/Ceiling Fan/level"
    payload_low_speed: 33
    payload_medium_speed: 66
    payload_high_speed: 100
    retain: true

# Phone Detection
device_tracker:
    - platform: netgear
      host: 10.99.10.1
      port: 80
      username: !secret netgear_user
      password: !secret netgear_pass
      devices:
          - BILLS-GALAXY-S8
          - Cricket-Moto-Z
