# MQTT
#mqtt:
#  broker: localhost
#  port: 1883
#  client_id: home-assistant-7718
#  keepalive: 60
#  #username: !secret mqtt_username
#  #password: !secret mqtt_password
#  discovery: true
#  discovery_prefix: ha-7718

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 34.718548
  longitude: -86.778091
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  #time_zone: US/Central
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   # uncomment this to enable backwards compatible API password support
   # - type: legacy_api_password

system_health:

recorder:
  purge_keep_days: 2
  db_url: 'sqlite:///:memory:'
  exclude:
    entities:
      - sun.sun

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend: !include frontend.yaml

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: https://bakerbug.duckdns.org:8123
  ssl_certificate: /home/homeassistant/dehydrated/certs/bakerbug.duckdns.org/fullchain.pem
  ssl_key: /home/homeassistant/dehydrated/certs/bakerbug.duckdns.org/privkey.pem
  #api_password: !secret api_key
  cors_allowed_origins:
    - http://10.99.10.7:7080

duckdns:
  domain: bakerbug
  access_token: !secret duckdns_token

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

wemo:
  discovery: false
  static:
    - 10.99.10.20
    - 10.99.10.21
    - 10.99.10.22
    - 10.99.10.23
    - 10.99.10.24
    - 10.99.10.25
    - 10.99.10.26
    - 10.99.10.27
    - 10.99.10.28
    - 10.99.10.29


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
    use_include_order: True
    include:
        entities:
            - weather.dark_sky
            - sun.sun
            - binary_sensor.workday
            - binary_sensor.bayberry_away
            - sensor.bill_location
            - sensor.cricket_location
            - lock.front_door
            - cover.left_bay
            - cover.right_bay
            - binary_sensor.ring_front_door_motion
            - binary_sensor.ring_driveway_cam_motion
            - binary_sensor.ring_backyard_cam_motion
            - sensor.upstairs_thermostat_temperature
            - sensor.downstairs_thermostat_temperature
            - sensor.weather_temperature
            - sensor.upstairs_thermostat_humidity
            - sensor.downstairs_thermostat_humidity
            - sensor.weather_humidity
            - sensor.upstairs_thermostat_hvac_state
            - sensor.downstairs_thermostat_hvac_state
            - sensor.fan_speed
            - sensor.bedroom_fan_speed
            - switch.wemo_alpha
            - switch.humidifier
            - switch.03200121dc4f221ad1cf_2
            - sensor.sleepnumber_bill_bill_sleepnumber
            - sensor.sleepnumber_bill_cricket_sleepnumber
            - binary_sensor.sleepnumber_bill_bill_is_in_bed
            - binary_sensor.sleepnumber_bill_cricket_is_in_bed
            - media_player.living_room
            - media_player.bedroom_tv
            - switch.driveway_light
            - switch.frontdoor_light
            - switch.patio_light
            - switch.bedroom_lamp
            - switch.04200320b4e62d1291c4_1
            - switch.04200320b4e62d1291c4_4
            - switch.wemo_echo
            - switch.entry_lamp
            - switch.sofa_lamp
            - switch.0120099868c63aa67ad8_2
            - switch.0120099868c63aa67ad8_3
            - switch.0120099868c63aa67ad8_4
            - switch.sink_light
            - group.counter_lights
            - group.ceiling_lights
            - switch.wemo_bravo
            - switch.wemo_charlie
            - switch.wemo_delta
    exclude:
        domains:
            - automation
        entities:
            - sensor.bayberry_eta
            - sensor.weather_symbol
            - group.bed
            - group.garage
            - switch.fan_control

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Custom Sensors
sensor:
  - platform: time_date
    display_options:
      - 'time'
  - platform: template
    sensors:
      fan_speed:
        friendly_name: "Ceiling Fan Speed"
        value_template: "{{ states.fan.living_room_ceiling_fan.attributes.speed }}"
      bedroom_fan_speed:
        friendly_name: "Bedroom Fan Speed"
        value_template: "{{ states.fan.bedroom_fan.attributes.speed }}"
      sun_elevation:
        friendly_name: "Sun Elevation"
        value_template: "{{ states.sun.sun.attributes.elevation }}"
      bill_location:
        friendly_name: "Bill's Location"
        value_template: "{{ states.device_tracker.life360_bill_baker.attributes.place }}"
      cricket_location:
        friendly_name: "Cricket's Location"
        value_template: "{{ states.device_tracker.life360_cricket.attributes.place }}"
      last_alexa:
        friendly_name: "Active Alexa"
        entity_id:
          - media_player.computer_room
          - media_player.kitchen
          - media_player.kyle_s_room
          - media_player.master_bedroom
          - media_player.upstairs
        value_template: >
          {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
      washing_machine_power:
        friendly_name: "Washing Machine Power"
        value_template: "{{ states.switch.washing_machine.attributes.current_power_w }}"
        unit_of_measurement: "Watts"
      weather_humidity:
        friendly_name: "Outdoor Humidity"
        unit_of_measurement: "%"
        value_template: "{{ states.weather.dark_sky.attributes.humidity }}"
      weather_temperature:
        friendly_name: "Outdoor Temperature"
        unit_of_measurement: "\u00B0F"
        value_template: "{{ states.weather.dark_sky.attributes.temperature }}"

    # Add 1 year for birthdays.
  - platform: anniversaries
    name: Bill's Birthday
    date: !secret bday_bill
  - platform: anniversaries
    name: Cricket's Birthday
    date: !secret bday_cricket
  - platform: anniversaries
    name: Kyle's Birthday
    date: !secret bday_kyle
  # Baker
  - platform: anniversaries
    name: Brian Baker's Birthday
    date: !secret bday_brian
  - platform: anniversaries
    name: Bill Baker's Birthday
    date: !secret bday_dad
  - platform: anniversaries
    name: Sharon Baker's Birthday
    date: !secret bday_sharon
  - platform: anniversaries
    name: Barbara Baker's Birthday
    date: !secret bday_mom
  # Davis
  - platform: anniversaries
    name: Kelly Davis' Birthday
    date: !secret bday_kelly
  - platform: anniversaries
    name: Gavin Davis' Birthday
    date: !secret bday_gavin





  - platform: version
    name: Installed HA Version
    source: local

  - platform: version
    name: Available HA Version
    source: pypi

# Custom Switches
switch:
  - platform: template
    switches:
      fan_control:
        friendly_name: "Fan Control"
        value_template: "{{ is_state('automation.hvac_balancing', 'on') }}"
        turn_on:
          - service: automation.turn_on
            data:
              entity_id: automation.hvac_balancing
          - service: python_script.fan_control
        turn_off:
          service: automation.turn_off
          data:
            entity_id: automation.hvac_balancing
      humidifier:
        friendly_name: "Humidifier"
        value_template: "{{ is_state('switch.0120099868c63aa67ad8_1', 'on') }}"
        turn_on:
          - service: switch.turn_on
            data:
              entity_id: switch.0120099868c63aa67ad8_1
          - service: automation.turn_off
            data:
              entity_id: automation.restart_humidifier
        turn_off:
          - service: automation.turn_on
            data:
              entity_id: automation.restart_humidifier
          - service: switch.turn_off
            data:
              entity_id: switch.0120099868c63aa67ad8_1


# Text to speech
#tts:
#  - platform: google_translate
#    service_name: google_say

# Cloud
cloud:
  alexa:
    filter:
      include_entities:
        - cover.left_bay
        - cover.right_bay
        - switch.fan_control
        - switch.humidifier
        - input_boolean.bus_notify
        - input_boolean.status_report
      exclude_domains:
        - alert
        - automation
        - fan
        - group
        - input_boolean
        - light
        - lock
        - media_player
        - scene
        - script
        - sensor
        - switch
      exclude_entities:
        - climate.downstairs
        - climate.upstairs

# Alexa media
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
      include_devices:
        - "Kitchen"
        - "Computer Room"
        - "Upstairs"
        - "Master Bedroom"
        - "Kyle's Room"

# HACS Home Assistant Community Store
hacs:
  token: !secret github_token

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Python script support
python_script:

# Garage Doors
cover:
  - platform: myq
    username: !secret chamberlain_username
    password: !secret chamberlain_password
    type: chamberlain

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_api_key

# Plex
#media_player:
#  - platform: plex

# Sleep Number Bed
sleepiq:
  username: !secret sleepnumber_user
  password: !secret sleepnumber_password

# Slack
notify:
  - name: Slack_Assistant
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#home'

# Tuya - Smart Life - Smart Power Strips
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1
  platform: 'smart_life'

# Security Cameras
ring:
  username: !secret ring_username
  password: !secret ring_password
camera:
    - platform: ring
ffmpeg:

## Phone Detection
#device_tracker:
#    - platform: netgear
#      host: 10.99.10.1
#      port: 80
#      username: !secret netgear_user
#      password: !secret netgear_pass
#      accesspoints:
#          - A0:40:A0:5A:03:D6
#      devices:
#          - BILLS-GALAXY-S8
#          - Cricket-Moto-Z

# Life 360
life360:
  accounts:
    - username: !secret life360_user
      password: !secret life360_pass

# Custom Sensors
binary_sensor:
    - platform: workday
      name: Workday
      country: US
    - platform: ring
      monitored_conditions: motion

# Timers
timer:
  motion_debounce:
    duration: '00:01:00'

input_boolean:
  bus_notify:
    name: Bus Notify
    icon: mdi:bus-school
  debug_alexa_speak:
    icon: mdi:bug-check-outline
  debug_bus_notify:
    icon: mdi:bug-check-outline
  notify_away_monitor:
    icon: mdi:message-text
  debug_fan_control:
    icon: mdi:bug-check-outline
  notify_fan_control:
    icon: mdi:message-text
  debug_laundry:
    icon: mdi:bug-check-outline
  announce_all:
    name: Alexa Anouncements
    icon: mdi:amazon-alexa
  announce_location_monitor:
    name: Announce Locations
    icon: mdi:amazon-alexa
  announce_oven_monitor:
    name: Announce Oven Temperature
    icon: mdi:amazon-alexa
  debug_location_monitor:
    icon: mdi:bug-check-outline
  notify_location_monitor:
    icon: mdi:message-text
  active_pollen_monitor:
    name: Pollen Alert
    icon: mdi:amazon-alexa
  debug_pollen_monitor:
    icon: mdi:bug-check-outline
  notify_pollen_monitor:
    icon: mdi:message-text
  debug_reminders:
    icon: mdi:bug-check-outline
  debug_version_monitor:
    icon: mdi:bug-check-outline
  status_report:
    icon: mdi:amazon-alexa

## Pollen Sensor
#iqvia:
#  zip_code: "35758"
#  monitored_conditions:
#    - allergy_index_today
#    - allergy_index_tomorrow
