homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 34.718548
  longitude: -86.778091
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: US/Central
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: https://bakerbug.duckdns.org:8123
  ssl_certificate: /home/homeassistant/.homeassistant/fullchain.pem
  ssl_key: /home/homeassistant/.homeassistant/privkey.pem
  api_password: !secret api_key
  cors_allowed_origins:
    - http://10.99.10.7:7080

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
    exclude:
        domains:
            - automation
        entities:
            - sensor.bayberry_eta
            - sensor.weather_symbol
            - group.bed
            - group.garage

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: Weather
    

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://10.99.10.7:3218

# Python script support
python_script:

# Garage Doors
cover:
  - platform: myq
    hidden: true
    username: !secret chamberlain_username
    password: !secret chamberlain_password
    type: chamberlain
    
# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  
# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    
# Plex
#media_player:
#  - platform: plex

# Sleep Number Bed
sleepiq:
  username: !secret sleepnumber_user
  password: !secret sleepnumber_password


