- id: '1531343546892'
  alias: Coffee Timer
  trigger:
  - entity_id: switch.03200121dc4f221ad1cf_2
    for: '1:00:00'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.03200121dc4f221ad1cf_2
    service: switch.turn_off
- id: '1531347206490'
  alias: Restart Humidifier
  initial_state: 'off'
  trigger:
  - entity_id: switch.humidifier
    for:
      minutes: 60
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.humidifier
    service: switch.turn_on
  - data:
      entity_id: automation.restart_humidifier
    service: automation.turn_off
- id: '1531918562375'
  alias: Lights on at Early Sunset
  trigger:
  - event: sunset
    offset: -01:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.evening_early_lights
    service: switch.turn_on
- id: '8881234567890'
  alias: Lights on at Sunset
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.evening_lights
    service: light.turn_on
  - data:
      entity_id: group.accent_lights
    service: switch.turn_on
  mode: single
- id: '1534730679270'
  alias: Lights Off When Away
  trigger:
  - at: '23:15:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.bayberry_away
    state: 'on'
  action:
  - data:
      entity_id: group.all_indoor_lights
    service: switch.turn_off
- id: '1537990954788'
  alias: Lights On When Away
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.away_lights
    service: switch.turn_on
- id: '1542775976127'
  alias: Watch TV - Start
  trigger:
  - entity_id: remote.harmony_hub
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.0120099868c63aa67ad8_1
    service: switch.turn_off
- id: '1542776135207'
  alias: Watch TV - Stop
  trigger:
  - entity_id: remote.harmony_hub
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.0120099868c63aa67ad8_1
    service: switch.turn_on
  - data:
      entity_id: automation.restart_humidifier
    service: automation.turn_off
- id: '1531365279143'
  alias: Kyles Reading Light Timer
  trigger:
  - entity_id: light.kyle_s_light
    for: 0:20:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    service: light.turn_off
    target:
      entity_id: light.kyle_s_light
  mode: single
- id: '1551361947987'
  alias: Exterior Lights on at Sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.driveway_light
    service: switch.turn_on
  - data:
      entity_id: switch.frontdoor_light
    service: switch.turn_on
- id: '1551362916030'
  alias: Exterior Lights Off
  trigger:
  - at: '21:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: timer.motion_debounce
    service: timer.start
  - data:
      entity_id: switch.driveway_light
    service: switch.turn_off
  - data:
      entity_id: switch.frontdoor_light
    service: switch.turn_off
- id: '1531353746820'
  alias: Patio Light Timer
  trigger:
  - entity_id: switch.patio_light
    for:
      minutes: 30
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.patio_light
    service: switch.turn_off
- id: '1555681619395'
  alias: Front Door Motion
  trigger:
  - entity_id: binary_sensor.front_door_cam_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.frontdoor_light
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: switch.frontdoor_light
    service: switch.turn_on
  - delay: 00:05:00
  - data:
      entity_id: switch.frontdoor_light
    service: switch.turn_off
- id: '1555681619396'
  alias: Driveway Motion
  trigger:
  - entity_id: binary_sensor.driveway_cam_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: timer.motion_debounce
    state: idle
  - condition: state
    entity_id: switch.driveway_light
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: switch.driveway_light
    service: switch.turn_on
  - delay: 00:05:00
  - data:
      entity_id: timer.motion_debounce
    service: timer.start
  - data:
      entity_id: switch.driveway_light
    service: switch.turn_off
- id: '1559082914918'
  alias: Pollen Monitor
  trigger:
  - at: '18:00:00'
    platform: time
  condition: []
  action:
  - service: python_script.pollen_monitor
- id: '1569264293957'
  alias: Arrive Home from Work
  trigger:
  - entity_id: sensor.bill_location
    platform: state
    to: Home
  - entity_id: sensor.cricket_location
    platform: state
    to: Home
  condition:
  - after: '16:00:00'
    before: '18:00:00'
    condition: time
  action:
  - alias: ''
    data:
      entity_id: cover.right_bay
    service: cover.open_cover
  - data:
      entity_id: cover.left_bay
    service: cover.open_cover
- id: '1572571564942'
  alias: Washing Machine Power On
  description: ''
  trigger:
  - entity_id: switch.washing_machine
    for: 0:01:00
    platform: state
    to: 'off'
  condition: []
  action:
  - alias: ''
    data:
      entity_id: switch.washing_machine
    service: switch.turn_on
- id: '1592455156353'
  alias: Secure the House
  description: ''
  trigger:
  - entity_id: input_boolean.secure_house
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - scene: scene.secure_the_house
  - data: {}
    entity_id: input_boolean.secure_house
    service: input_boolean.turn_off
- id: '1592455156354'
  alias: Turn Off the Printer
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  action:
  - data:
      entity_id: switch.wemo_delta
    service: switch.turn_off
- id: '1594143806866'
  alias: Power Off PS4
  description: ''
  trigger:
  - entity_id: media_player.playstation_4
    for: 00:05:00
    platform: state
    to: standby
  - entity_id: media_player.playstation_4
    for: 00:05:00
    platform: state
    to: unknown
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ (state_attr(''remote.harmony_hub'', ''current_activity''))
        == ''Play PS4'' }}'
  action:
  - data: {}
    entity_id: remote.harmony_hub
    service: remote.turn_off
  mode: single
- id: '1596166060300'
  alias: Shelf Lights On
  description: ''
  trigger:
  - entity_id: remote.harmony_hub
    from: 'on'
    platform: state
    to: 'off'
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: and
    conditions:
    - condition: state
      entity_id: remote.harmony_hub
      state: 'off'
  action:
  - device_id: 8d49c4eb63064e5d971a925ec1dce2ad
    domain: switch
    entity_id: switch.0120099868c63aa67ad8_4
    type: turn_on
  mode: single
- id: '1596166185310'
  alias: Shelf Lights Off
  description: ''
  trigger:
  - entity_id: remote.harmony_hub
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - device_id: 8d49c4eb63064e5d971a925ec1dce2ad
    domain: switch
    entity_id: switch.0120099868c63aa67ad8_4
    type: turn_off
  mode: single
- id: '1596613817892'
  alias: Turn Off Tower Fan
  description: ''
  trigger:
  - at: '22:00:00'
    platform: time
  condition: []
  action:
  - device_id: 232fe132fd4f42f1b76cb4f510bdc28a
    domain: switch
    entity_id: switch.wemo_charlie
    type: turn_off
  - delay: 0:01:00
  - device_id: 232fe132fd4f42f1b76cb4f510bdc28a
    domain: switch
    entity_id: switch.wemo_charlie
    type: turn_on
  mode: single
- id: '1598452535055'
  alias: Weekday Morning Lights Off
  description: ''
  trigger:
  - at: 08:00:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday
    state: 'on'
  action:
  - data:
      entity_id: group.all_indoor_lights
    service: switch.turn_off
  mode: single
- id: '1610311093833'
  alias: Enable Tesla HVAC
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.tesla_hvac_enable
    from: 'off'
    to: 'on'
  condition: []
  action:
  - device_id: 4db4a7fdfa1b11ea81750701e75842de
    domain: climate
    entity_id: climate.meco_hvac_climate_system
    type: set_hvac_mode
    hvac_mode: heat_cool
  - service: switch.turn_on
    data: {}
    entity_id: switch.meco_update_switch
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.tesla_hvac_enable
  mode: single
- id: '1614023298970'
  alias: Tesla - Disable Polling
  description: Disable polling when at home and fully charged.
  trigger:
  - platform: state
    entity_id: sensor.meco_charging_rate_sensor
    to: '0.0'
    for: 00:15:00
  condition:
  - condition: state
    entity_id: binary_sensor.meco_charger_sensor
    state: 'on'
  - condition: state
    entity_id: device_tracker.meco_location_tracker
    state: home
  action:
  - type: turn_off
    device_id: 4db4a7fdfa1b11ea81750701e75842de
    entity_id: switch.meco_update_switch
    domain: switch
  mode: single
- id: '1615398511068'
  alias: Tesla - Enable Polling
  description: Enables polling when someone departs
  trigger:
  - platform: state
    entity_id: device_tracker.life360_bill_baker
    from: home
  - platform: state
    entity_id: device_tracker.life360_cricket
    from: home
  condition:
  - condition: state
    entity_id: cover.right_bay
    state: open
  action:
  - type: turn_on
    device_id: 4db4a7fdfa1b11ea81750701e75842de
    entity_id: switch.meco_update_switch
    domain: switch
  mode: single
- id: '1618931632586'
  alias: Lava Lamp - Morning Turn On
  description: Turn on the Lava Lamp every mornings
  trigger:
  - platform: time
    at: 06:00
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.lava_lamp
  mode: single
- id: '1618931692851'
  alias: Lava Lamp - Morning Turn Off
  description: ''
  trigger:
  - platform: time
    at: '12:00'
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.lava_lamp
  mode: single
- id: '1618931786001'
  alias: Lava Lamp - Evening Turn On
  description: ''
  trigger:
  - platform: time
    at: '17:30'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.lava_lamp
  mode: single
- id: '1618931854773'
  alias: Lava Lamp - Evening Turn Off
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.lava_lamp
  mode: single
