
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
config:
  customize: !include customize.yaml
frontend:
  themes: !include_dir_merge_named themes

http:
  base_url: https://bakerbug.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  cors_allowed_origins:
    - http://10.99.10.10:8123

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 7
  db_url: 'sqlite:///:memory:'
  exclude:
    entities:
      - sun.sun

# Cloud
cloud:
  alexa:
    filter:
      include_entities:
        - cover.left_bay
        - cover.right_bay
        - switch.fan_control
        - switch.humidifier
      exclude_domains:
        - alert
        - automation
        - fan
        - group
        - light
        - lock
        - media_player
        - scene
        - script
        - sensor
        - switch
      exclude_entities:
        - climate.downstairs
        - climate.upstairs

# Alexa media
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
      include_devices:
        - "Kitchen"
        - "Computer Room"
        - "Upstairs"
        - "Master Bedroom"
        - "Kyle's Room"
        - "Bill's Echo Auto"

history:
    use_include_order: True
    include:
        entities:
            - weather.khsv
            - sun.sun
            - binary_sensor.workday
            - binary_sensor.bayberry_away
            - sensor.bill_location
            - sensor.cricket_location
            - lock.front_door
            - lock.back_door
            - cover.left_bay
            - cover.right_bay
            - binary_sensor.front_door_cam_motion
            - binary_sensor.driveway_cam_motion
            - binary_sensor.backyard_cam_motion
            - sensor.master_bedroom_nest_protect_smoke_status
            - sensor.kids_room_nest_protect_smoke_status
            - sensor.master_bedroom_nest_protect_co_status
            - sensor.kids_room_nest_protect_co_status
            - sensor.upstairs_thermostat_temperature
            - sensor.downstairs_thermostat_temperature
            - sensor.weather_temperature
            - sensor.upstairs_thermostat_humidity
            - sensor.downstairs_thermostat_humidity
            - sensor.weather_humidity
            - sensor.upstairs_thermostat_hvac_state
            - sensor.downstairs_thermostat_hvac_state
            - sensor.fan_speed
            - sensor.bedroom_fan_speed
            - switch.wemo_alpha
            - switch.humidifier
            - switch.03200121dc4f221ad1cf_2
            - sensor.sleepnumber_bill_bill_sleepnumber
            - sensor.sleepnumber_bill_cricket_sleepnumber
            - binary_sensor.sleepnumber_bill_bill_is_in_bed
            - binary_sensor.sleepnumber_bill_cricket_is_in_bed
            - media_player.living_room
            - media_player.playstation_4
            - media_player.bedroom_tv
            - switch.driveway_light
            - switch.frontdoor_light
            - switch.patio_light
            - switch.bedroom_lamp
            - switch.04200320b4e62d1291c4_1
            - switch.04200320b4e62d1291c4_4
            - light.bedroom_dimmer
            - switch.wemo_echo
            - switch.entry_lamp
            - switch.sofa_lamp
            - switch.0120099868c63aa67ad8_2
            - switch.0120099868c63aa67ad8_3
            - switch.0120099868c63aa67ad8_4
            - switch.sink_light
            - group.counter_lights
            - group.ceiling_lights
            - switch.dining_room_light
            - switch.wemo_bravo
            - switch.wemo_charlie
            - switch.wemo_delta
    exclude:
        domains:
            - automation
        entities:
            - sensor.bayberry_eta
            - sensor.weather_symbol
            - group.bed
            - group.garage
            - switch.fan_control

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret


# Sensors
sensor:
  - platform: time_date
    display_options:
      - 'time'
  - platform: template
    sensors:
      fan_speed:
        friendly_name: "Ceiling Fan Speed"
        value_template: "{{ states.fan.living_room_ceiling_fan.attributes.speed }}"
      bedroom_fan_speed:
        friendly_name: "Bedroom Fan Speed"
        value_template: "{{ states.fan.bedroom_fan.attributes.speed }}"
      sun_elevation:
        friendly_name: "Sun Elevation"
        value_template: "{{ states.sun.sun.attributes.elevation }}"
      bill_location:
        friendly_name: "Bill's Location"
        value_template: "{{ states.device_tracker.life360_bill_baker.attributes.place }}"
      cricket_location:
        friendly_name: "Cricket's Location"
        value_template: "{{ states.device_tracker.life360_cricket.attributes.place }}"
      last_alexa:
        friendly_name: "Active Alexa"
        entity_id:
          - media_player.computer_room
          - media_player.kitchen
          - media_player.kyle_s_room
          - media_player.master_bedroom
          - media_player.upstairs
          - media_player.echo_auto_camry
        value_template: >
          {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
      washing_machine_power:
        friendly_name: "Washing Machine Power"
        value_template: "{{ states.switch.washing_machine.attributes.current_power_w }}"
        unit_of_measurement: "Watts"
      weather_humidity:
        friendly_name: "Outdoor Humidity"
        unit_of_measurement: "%"
        value_template: "{{ states.weather.khsv.attributes.humidity }}"
      weather_temperature:
        friendly_name: "Outdoor Temperature"
        unit_of_measurement: "\u00B0F"
        value_template: "{{ states.weather.khsv.attributes.temperature }}"

  - platform: version
    name: Installed HA Version
    source: local

  - platform: version
    name: Available HA Version
    source: pypi

  - platform: weatheralerts
    state: AL
    zone: 6
    county: 89

# Slack
notify:
  - name: Slack_Assistant
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#home'

python_script:

# Sleep Number Bed
sleepiq:
  username: !secret sleepnumber_user
  password: !secret sleepnumber_password

# Custom Sensors
binary_sensor:
    - platform: workday
      name: Workday
      country: US

# Custom Switches
switch:
  - platform: template
    switches:
      fan_control:
        friendly_name: "Fan Control"
        value_template: "{{ is_state('automation.hvac_balancing', 'on') }}"
        turn_on:
          - service: automation.turn_on
            data:
              entity_id: automation.hvac_balancing
          - service: python_script.fan_control
        turn_off:
          service: automation.turn_off
          data:
            entity_id: automation.hvac_balancing
      humidifier:
        friendly_name: "Humidifier"
        value_template: "{{ is_state('switch.0120099868c63aa67ad8_1', 'on') }}"
        turn_on:
          - service: switch.turn_on
            data:
              entity_id: switch.0120099868c63aa67ad8_1
          - service: automation.turn_off
            data:
              entity_id: automation.restart_humidifier
        turn_off:
          - service: automation.turn_on
            data:
              entity_id: automation.restart_humidifier
          - service: switch.turn_off
            data:
              entity_id: switch.0120099868c63aa67ad8_1

# Timers
timer:
  motion_debounce:
    duration: '00:01:00'
  wakup_light:
    duration: '00:02:00'

input_boolean:
  announce_all:
    name: Alexa Anouncements
    icon: mdi:amazon-alexa
  active_sleep_monitor:
    name: Sleep Monitor
    icon: mdi:language-python
  bus_notify:
    name: Bus Notify
    initial: off
    icon: mdi:bus-school
  fireplace_temperature:
    name: Fireplace Temperature
    initial: off
    icon: mdi:fireplace
  location_monitor:
    name: Location Monitor
    icon: mdi:map-marker
  satellite_report:
    name: Satellite Report
    icon: mdi:space-station
  secure_house:
    name: Secure The House
    icon: mdi:shield-home-outline
  wakeup_light:
    name: Wakeup Light
    icon: mdi:alarm
  wakeup_light_weekend:
    name: Weekend Wakeup Light
    icon: mdi:alarm

  # DEBUG
  debug_alexa_speak:
    icon: mdi:bug-check-outline
  debug_bus_notify:
    icon: mdi:bug-check-outline
  debug_fan_control:
    icon: mdi:bug-check-outline
  debug_fireplace_temp:
    icon: mdi:bug-check-outline
  debug_garage_monitor:
    icon: mdi:bug-check-outline
  debug_laundry:
    icon: mdi:bug-check-outline
  debug_location_monitor:
    icon: mdi:bug-check-outline
  debug_pollen_monitor:
    icon: mdi:bug-check-outline
  debug_reminders:
    icon: mdi:bug-check-outline
  debug_satellite_monitor:
    icon: mdi:bug-check-outline
  debug_sleep_monitor:
    icon: mdi:bug-check-outline
  debug_version_monitor:
    icon: mdi:bug-check-outline
  debug_wakeup_light:
    icon: mdi:bug-check-outline

  # NOTIFY
  notify_away_monitor:
    icon: mdi:message-text

  notify_fan_control:
    icon: mdi:message-text

  announce_location_change:
    name: Announce Locations
    icon: mdi:amazon-alexa
  announce_lock_change:
    name: Announce Lock Change
    icon: mdi:key-variant
  announce_oven_monitor:
    name: Announce Oven Temperature
    icon: mdi:amazon-alexa

  notify_location_monitor:
    icon: mdi:message-text
  respond_pollen_monitor:
    name: Pollen Monitor Response
    icon: mdi:tree-outline

  notify_pollen_monitor:
    icon: mdi:message-text

  status_report:
    icon: mdi:amazon-alexa

input_number:
  fireplace_max_indoor_temp:
    name: Max Indoor Temperature
    min: 65
    max: 70
    icon: mdi:fireplace
  fireplace_max_outdoor_temp:
    name: Max Outdoor Temperature
    min: 45
    max: 60
    icon: mdi:fireplace
  bedroom_fan_low_temp:
    name: Bedroom Fan Low Temperature
    min: 65
    max: 75
    icon: mdi:fan

input_datetime:
  wakeup_time:
    name: Wakeup Time
    has_date: false
    has_time: true
    icon: mdi:alarm

