all_indoor_lights:
  name: All Indoor Lights
  entities:
    - group.living_area_lights
    - group.bedroom_lights
    - group.accent_lights
    - light.kyle_s_light
    - light.dining_room_light
    - light.garage_light
    - light.guest_bathroom
all_outdoor_lights:
  name: All Outdoor Lights
  entities:
    - light.driveway_light
    - light.front_door_light
    - light.patio_light
accent_lights:
  name: Accent Lights
  entities:
    - light.corner_lamp
    - light.lava_lamp
    - light.bottle_lamp
appliances:
  name: Appliances
  entities:
    - switch.03200121dc4f221ad1cf_2
    - switch.wemo_alpha
away_lights:
  name: Away Lights
  entities:
    - light.ceiling_lights
    - light.sky_lights
    - light.dining_room_light
evening_early_lights:
  name: Early Evening Lights
  entities:
    - light.entry_lamp
    - light.sofa_lamp
    - light.counter_lights
    - light.bottle_lamp
evening_lights:
  name: Evening Lights
  entities:
    - light.ceiling_lights
    - light.sky_lights
    - light.corner_lamp
late_night_lights:
  name: Late Night Lights
  entities:
    - light.bottle_lamp
    - light.corner_lamp
bedroom_lights:
  name: Bedroom Lights
  entities:
    - light.bedroom_lamp
    - light.bill_s_lamp
    - light.cricket_s_lamp
    - light.bedroom_dimmer
garage_doors:
  name: Garage Doors
  entities:
    - cover.left_bay
    - cover.right_bay
kitchen_lights:
  name: Kitchen Lights
  entities:
    - light.island_light
    - light.sink_light
    - light.counter_lights
    - light.ceiling_lights
kyle_room:
  name: Kyle's Room
  entities:
    - light.kyles_light
    - light.lava_lamp
livingroom_lights:
  name: Living Room Lights
  entities:
    - light.entry_lamp
    - light.sofa_lamp
    - light.sky_lights
    - light.corner_lamp
    - light.shelf_lights
    - light.bottle_lamp
living_area_lights:
  name: Living Area Lights
  entities:
    - group.kitchen_lights
    - group.livingroom_lights
    - light.dining_room_light
morning_lights:
  name: Morning Lights
  entities:
    - group.livingroom_lights
    - group.kitchen_lights
bed:
  name: Master Bed
  entities:
    - sensor.sleepnumber_bill_bill_sleepnumber
    - sensor.sleepnumber_bill_cricket_sleepnumber
    - binary_sensor.sleepnumber_bill_bill_is_in_bed
    - binary_sensor.sleepnumber_bill_cricket_is_in_bed
smart_switches:
  name: Smart Switches
  entities:
    - switch.fan_control
    - switch.humidifier

